# This workflow will do a clean installation of node dependencies, cache/restore them and build the source code across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '^20.11'
        check-latest: true
        cache: 'npm'
    - run: pwd
    - run: ls -la
    - run: npm i
    - run: npm ci
    - run: npm run build --if-present
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: website-content
        path: build
        retention-days: 1
  deploy:
      if: github.event_name != 'pull_request'
      needs: build
      runs-on: ubuntu-latest
      environment: web-production
      steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: website-content
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASS }}
          local-dir: dist