# This workflow will do a clean installation of node dependencies, cache/restore them and build the source code across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.16
      uses: actions/setup-node@v3
      with:
        node-version: 18.16
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - run: npm ci
    - run: npm run build --if-present